version: 2.1
orbs:
  node: circleci/node@5.2.0
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - browser-tools/install-chrome: 
          channel: stable
      - node/install-packages:
          app-dir: ./alexnmdev
      - run:
          working_directory: ./alexnmdev
          command: npm run test
          filters:
            branches:
              only:
                - main

workflows:
  test_my_app:
    jobs:
      - test
